((lambda (pow x) 
    (if (eq? (pow x) 100) 
        (pow (pow (pow (/ x 2))))
        (pow (pow (pow x)))
    )
)(lambda (x) (* x x)) 10)
(
    ((lambda (a b) 
        (lambda (f) 
            (f (- a b)))
    ) 20 30) (lambda (x) (* x 2))
)